CREATE TABLE User (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
FirstName VARCHAR(20) NOT NULL ,
MiddleName VARCHAR(30) NOT NULL ,
LastName VARCHAR(30) NOT NULL ,
UserGroup INTEGER NOT NULL 
);

CREATE TABLE Role (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
Name VARCHAR(20) NOT NULL ,
Description VARCHAR(255) NOT NULL ,
Permission INTEGER NOT NULL 
);

CREATE TABLE UserGroup (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
Name VARCHAR(20) NOT NULL ,
Description VARCHAR(255) NOT NULL 
);

CREATE TABLE Authentication (
User INTEGER NOT NULL ,
PasswordHash VARCHAR(33) NOT NULL ,
UNIQUE (User, PasswordHash)
);

CREATE TABLE UserGroupRoles (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
UserGroup INTEGER NOT NULL ,
Role INTEGER NOT NULL 
);

